<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.a8kj.bukkitprojects</groupId>
    <artifactId>SlimeHologram</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>1.5.7-BETA</revision>
        <java.version>21</java.version>
        <spigot.version>R</spigot.version>
        <packetevents.version>2.12.0</packetevents.version>
        <lombok.version>1.18.32</lombok.version>
        <papi.version>2.11.6</papi.version>
        <shade.plugin.version>3.5.2</shade.plugin.version>
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <module>constants</module>
        <module>util</module>
        <module>api</module>
        <module>packet</module>
        <module>base</module>
    </modules>

    <repositories>
        <repository>
            <id>codemc-releases</id>
            <url>https://repo.codemc.io/repository/maven-releases/</url>
        </repository>
        <repository>
            <id>codemc-snapshots</id>
            <url>https://repo.codemc.io/repository/maven-snapshots/</url>
        </repository>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>

        <repository>
            <id>placeholderapi</id>
            <url>https://repo.extendedclip.com/content/repositories/placeholderapi/</url>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.github.azbh111</groupId>
                <artifactId>spigot-1.8.8</artifactId>
                <version>${spigot.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.github.retrooper</groupId>
                <artifactId>packetevents-spigot</artifactId>
                <version>${packetevents.version}</version>
                <scope>compile</scope>
            </dependency>


            <dependency>
                <groupId>me.clip</groupId>
                <artifactId>placeholderapi</artifactId>
                <version>${papi.version}</version>
                <scope>provided</scope>
            </dependency>

            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
                <scope>provided</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>${shade.plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>